image: 
- macOS
- Visual Studio 2022
- Ubuntu2204

environment:
  major: 4
  minor: 1
  release: 0
  app_version: '$(major).$(minor).$(release).$(APPVEYOR_BUILD_NUMBER)'

version: '$(major).$(minor).$(release).{build}'

build_script:
  - cmd: msbuild OSPSuite.SimModelSolver.CVODES.sln /property:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild OSPSuite.SimModelSolver.CVODES.sln /property:Configuration=Release;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  - sh: |
    if [ "$(uname)" == "Darwin" ]; 
    then
        Platform=MacOS
    else
        Platform=Ubuntu22
    fi
    cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.SimModelSolver_CVODES/ -DCMAKE_BUILD_TYPE=Release  -DlibCVODES=packages/CVODES.${Platform}/CVODES/bin/native/x64/Release/libsundials_cvodes.a
    make -C Build/Release/x64/
    cmake -BBuild/Debug/x64/ -Hsrc/OSPSuite.SimModelSolver_CVODES/ -DCMAKE_BUILD_TYPE=Debug  -DlibCVODES=packages/CVODES.${Platform}/CVODES/bin/native/x64/Debug/libsundials_cvodes.a
    make -C Build/Debug/x64/

before_build:
  - ps: (get-content src\OSPSuite.SimModelSolver_CVODES\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE $env:RELEASE" -replace "MAJOR 0", "MAJOR $env:MAJOR" -replace "MINOR 0", "MINOR $env:MINOR" -replace "BUILD 0", "BUILD $env:APPVEYOR_BUILD_NUMBER"} | set-content src\OSPSuite.SimModelSolver_CVODES\version.h
  # nuget packages are required by tests only which is currently performed on Windows only
  - cmd: nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - cmd: nuget install packages.config -OutputDirectory packages # cannot use automatic artifact publish because it's not recognized in a C++/CLI project

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - master
    - develop

pull_requests: 
  do_not_increment_build_number: true     

install:
  - cmd: git submodule update --init --recursive
  - sh: git submodule update --init --recursive

after_build:
  - cmd: dotnet pack src/OSPSuite.SimModelSolver_CVODES/pack.csproj -p:PackageVersion=%app_version% -o ./
  - sh: dotnet pack src/OSPSuite.SimModelSolver_CVODES/pack.csproj -p:PackageVersion=$app_version -o ./
  - ps: Get-ChildItem .\OSPSuite.SimModelSolver_CVODES.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
test:
  # currently tests are run on Windows only
  assemblies:
  - '**\*.Tests.Release.x64.dll'
  
skip_commits:
  files:
    - '*.md'

nuget:
  disable_publish_on_pr: true
